### ISSUE TITLE
Exception in plugin PHP Code Generator + (1.0).

### ISSUE THREAD

**Issue by cirrusa** [KristijanKanalas/PHPCodeGeneratorPlus#1]
```
java.lang.ClassCastException: class com.jetbrains.php.lang.psi.elements.impl.MethodImpl cannot be cast to class com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl (com.jetbrains.php.lang.psi.elements.impl.MethodImpl and com.jetbrains.php.lang.psi.elements.impl.PhpClassImpl are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @24857aba)
	at PHPCodeGenerator.GenerateMethodsService.generateMethods(GenerateMethodsService.java:52)
	at PHPCodeGenerator.GetSettersActionClass.actionPerformed(GetSettersActionClass.java:12)
```

**Comment by KristijanKanalas** [comment]
Sorry for long waiting time, I will work on this plugin more in future, I've been aware of this bug for some time so I'm leaving the issue opened until I get around fixing it.
